#ifndef MODALITY_PROBE_EVENTS_H
#define MODALITY_PROBE_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Tracing event IDs
 *
 * Naming convention is TRACE_EVENT_<CLASS>_<FUNCTION>.
 * The manifest-gen script generates event entries named <CLASS>_<FUNCTION>, e.g.
 * the event TRACE_EVENT_TASK_CREATE will be in the manifest as TASK_CREATE.
 * A <class> tag will also be added to the event's metadata.
 *
 */
#define TRACE_EVENT_ID_TOP (0xFFFF)

#define TRACE_EVENT_TASK_CREATE (TRACE_EVENT_ID_TOP - 1)
#define TRACE_EVENT_TASK_SWITCHED_IN (TRACE_EVENT_ID_TOP - 2)
#define TRACE_EVENT_TASK_SWITCHED_OUT (TRACE_EVENT_ID_TOP - 3)
#define TRACE_EVENT_TASK_SUSPEND (TRACE_EVENT_ID_TOP - 4)
#define TRACE_EVENT_TASK_DELAY (TRACE_EVENT_ID_TOP - 5)
#define TRACE_EVENT_TASK_DELAY_UNTIL (TRACE_EVENT_ID_TOP - 6)

#define TRACE_EVENT_QUEUE_SEND (TRACE_EVENT_ID_TOP - 100)
#define TRACE_EVENT_QUEUE_SEND_BLOCKED (TRACE_EVENT_ID_TOP - 101)
#define TRACE_EVENT_QUEUE_SEND_FAILED (TRACE_EVENT_ID_TOP - 102)
#define TRACE_EVENT_QUEUE_SEND_FRONT (TRACE_EVENT_ID_TOP - 103)
#define TRACE_EVENT_QUEUE_SEND_FRONT_BLOCKED (TRACE_EVENT_ID_TOP - 104)
#define TRACE_EVENT_QUEUE_SEND_FRONT_FAILED (TRACE_EVENT_ID_TOP - 105)
#define TRACE_EVENT_QUEUE_SEND_FROMISR (TRACE_EVENT_ID_TOP - 106)
#define TRACE_EVENT_QUEUE_SEND_FROMISR_FAILED (TRACE_EVENT_ID_TOP - 107)
#define TRACE_EVENT_QUEUE_SEND_FRONT_FROMISR (TRACE_EVENT_ID_TOP - 108)
#define TRACE_EVENT_QUEUE_SEND_FRONT_FROMISR_FAILED (TRACE_EVENT_ID_TOP - 109)

#define TRACE_EVENT_QUEUE_RECEIVE (TRACE_EVENT_ID_TOP - 200)
#define TRACE_EVENT_QUEUE_RECEIVE_BLOCKED (TRACE_EVENT_ID_TOP - 201)
#define TRACE_EVENT_QUEUE_RECEIVE_FAILED (TRACE_EVENT_ID_TOP - 202)
#define TRACE_EVENT_QUEUE_RECEIVE_FROMISR (TRACE_EVENT_ID_TOP - 203)
#define TRACE_EVENT_QUEUE_RECEIVE_FROMISR_FAILED (TRACE_EVENT_ID_TOP - 204)

#define TRACE_EVENT_SEMAPHORE_GIVE (TRACE_EVENT_ID_TOP - 300)
#define TRACE_EVENT_SEMAPHORE_GIVE_BLOCKED (TRACE_EVENT_ID_TOP - 301)
#define TRACE_EVENT_SEMAPHORE_GIVE_FAILED (TRACE_EVENT_ID_TOP - 302)
#define TRACE_EVENT_SEMAPHORE_GIVE_FROMISR (TRACE_EVENT_ID_TOP - 303)
#define TRACE_EVENT_SEMAPHORE_GIVE_FROMISR_FAILED (TRACE_EVENT_ID_TOP - 304)

#define TRACE_EVENT_SEMAPHORE_TAKE (TRACE_EVENT_ID_TOP - 400)
#define TRACE_EVENT_SEMAPHORE_TAKE_BLOCKED (TRACE_EVENT_ID_TOP - 401)
#define TRACE_EVENT_SEMAPHORE_TAKE_FAILED (TRACE_EVENT_ID_TOP - 402)
#define TRACE_EVENT_SEMAPHORE_TAKE_FROMISR (TRACE_EVENT_ID_TOP - 403)
#define TRACE_EVENT_SEMAPHORE_TAKE_FROMISR_FAILED (TRACE_EVENT_ID_TOP - 404)

#define TRACE_EVENT_MUTEX_GIVE (TRACE_EVENT_ID_TOP - 500)
#define TRACE_EVENT_MUTEX_GIVE_BLOCKED (TRACE_EVENT_ID_TOP - 501)
#define TRACE_EVENT_MUTEX_GIVE_FAILED (TRACE_EVENT_ID_TOP - 502)

#define TRACE_EVENT_MUTEX_TAKE (TRACE_EVENT_ID_TOP - 600)
#define TRACE_EVENT_MUTEX_TAKE_BLOCKED (TRACE_EVENT_ID_TOP - 601)
#define TRACE_EVENT_MUTEX_TAKE_FAILED (TRACE_EVENT_ID_TOP - 602)

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* MODALITY_PROBE_EVENTS_H */
